package com.example.domain

import com.example.model.CalculationChain
import com.example.model.ChainNode
import com.example.model.ChainNodeType
import com.example.model.ChainScenario
import kotlin.math.pow

object CalculationChainEngine {

    val BUILTIN_CHAINS = listOf(
        CalculationChain(
            id = "personal_wealth_cascade",
            title = "Personal Wealth & SIP Cascade",
            description = "Salary → Expenses → Savings → SIP Investment → Compounding Wealth (Exact linked reactive pipeline)",
            category = "Personal Finance",
            nodes = listOf(
                ChainNode(
                    id = "salary",
                    title = "Monthly Salary (Net Take-Home)",
                    type = ChainNodeType.SOURCE_INPUT,
                    primaryValue = 75000.0,
                    unit = "₹",
                    description = "Monthly in-hand income",
                    minValue = 1.0,
                    maxValue = 1000000.0,
                    step = 500.0
                ),
                ChainNode(
                    id = "expenses",
                    title = "Living Expenses & Rent",
                    type = ChainNodeType.SUBTRACT_AMOUNT,
                    primaryValue = 35000.0,
                    unit = "₹",
                    description = "Deducted monthly essential overhead",
                    minValue = 0.0,
                    maxValue = 500000.0,
                    step = 250.0
                ),
                ChainNode(
                    id = "investment_sip",
                    title = "Monthly SIP Investment Allocation",
                    type = ChainNodeType.PERCENTAGE_ALLOCATE,
                    primaryValue = 62.5, // 62.5% of remaining savings (40,000 * 62.5% = ₹25,000)
                    unit = "%",
                    description = "Percentage of monthly savings directed to SIP",
                    minValue = 0.0,
                    maxValue = 100.0,
                    step = 1.0
                ),
                ChainNode(
                    id = "compound_wealth",
                    title = "15-Year SIP Compound Corpus (at 12% CAGR)",
                    type = ChainNodeType.COMPOUND_GROWTH,
                    primaryValue = 12.0, // Expected annual return %
                    secondaryValue = 15.0, // 15 years
                    unit = "₹",
                    description = "Total future wealth generated by monthly compounding SIP",
                    minValue = 1.0,
                    maxValue = 30.0,
                    step = 0.5
                ),
                ChainNode(
                    id = "inflation_adjusted",
                    title = "Inflation Adjusted Purchasing Power (at 6% Inflation)",
                    type = ChainNodeType.PERCENTAGE_DEDUCT,
                    primaryValue = 58.27, // Purchasing power loss over 15 years at 6% = 1 - (1/1.06^15) ≈ 58.3%
                    unit = "₹",
                    description = "Real inflation-adjusted value in today's money",
                    minValue = 0.0,
                    maxValue = 90.0,
                    step = 1.0
                )
            )
        ),

        CalculationChain(
            id = "ecommerce_profit_funnel",
            title = "E-Commerce Unit Profit Funnel",
            description = "Product Sourcing → Packaging & Ship → Ad CAC → Price → Gateway & Tax → Net Margin",
            category = "Business & Sales",
            nodes = listOf(
                ChainNode(
                    id = "selling_price",
                    title = "Customer Retail Price",
                    type = ChainNodeType.SOURCE_INPUT,
                    primaryValue = 1499.0,
                    unit = "₹",
                    description = "Listed selling price on storefront",
                    minValue = 1.0,
                    maxValue = 50000.0,
                    step = 5.0
                ),
                ChainNode(
                    id = "sourcing_cost",
                    title = "Product Sourcing & Manufacturing",
                    type = ChainNodeType.SUBTRACT_AMOUNT,
                    primaryValue = 450.0,
                    unit = "₹",
                    description = "Factory procurement cost per unit",
                    minValue = 0.0,
                    maxValue = 20000.0,
                    step = 5.0
                ),
                ChainNode(
                    id = "shipping_packaging",
                    title = "Courier Shipping & Custom Box",
                    type = ChainNodeType.SUBTRACT_AMOUNT,
                    primaryValue = 120.0,
                    unit = "₹",
                    description = "Logistics and protective packing",
                    minValue = 0.0,
                    maxValue = 5000.0,
                    step = 5.0
                ),
                ChainNode(
                    id = "ad_cac",
                    title = "Customer Acquisition Cost (Ad Spend/Order)",
                    type = ChainNodeType.SUBTRACT_AMOUNT,
                    primaryValue = 380.0,
                    unit = "₹",
                    description = "Meta & Google Ads cost per purchase",
                    minValue = 0.0,
                    maxValue = 5000.0,
                    step = 5.0
                ),
                ChainNode(
                    id = "payment_gst",
                    title = "Payment Gateway Fee (2%) + Platform GST",
                    type = ChainNodeType.PERCENTAGE_DEDUCT,
                    primaryValue = 4.5,
                    unit = "%",
                    description = "Payment gateway and transactional taxes",
                    minValue = 0.0,
                    maxValue = 28.0,
                    step = 0.5
                ),
                ChainNode(
                    id = "monthly_scale",
                    title = "Monthly Net Profit (at 500 Orders)",
                    type = ChainNodeType.MULTIPLY_VALUE,
                    primaryValue = 500.0,
                    unit = "₹",
                    description = "Scale volume multiplier (units sold per month)",
                    minValue = 1.0,
                    maxValue = 10000.0,
                    step = 10.0
                )
            )
        ),

        CalculationChain(
            id = "fitness_macro_pipeline",
            title = "Calorie & Macronutrient Partitioning",
            description = "Target Weight → BMR → Activity → Deficit/Surplus → Protein, Fat & Carb Grams",
            category = "Health & Fitness",
            nodes = listOf(
                ChainNode(
                    id = "body_weight",
                    title = "Current Body Weight",
                    type = ChainNodeType.SOURCE_INPUT,
                    primaryValue = 72.0,
                    unit = "kg",
                    description = "Baseline body mass",
                    minValue = 1.0,
                    maxValue = 200.0,
                    step = 0.5
                ),
                ChainNode(
                    id = "bmr_maintenance",
                    title = "Basal Metabolic Rate + Daily Activity (TDEE)",
                    type = ChainNodeType.MULTIPLY_VALUE,
                    primaryValue = 30.0, // approx 30 kcal per kg
                    unit = "kcal",
                    description = "Daily maintenance calories burned",
                    minValue = 1.0,
                    maxValue = 45.0,
                    step = 0.5
                ),
                ChainNode(
                    id = "calorie_deficit",
                    title = "Fat Loss Calorie Deficit",
                    type = ChainNodeType.SUBTRACT_AMOUNT,
                    primaryValue = 400.0,
                    unit = "kcal",
                    description = "Target daily caloric intake for sustained weight loss",
                    minValue = 0.0,
                    maxValue = 1000.0,
                    step = 25.0
                ),
                ChainNode(
                    id = "protein_target",
                    title = "Daily Protein Intake (2.0g per kg bodyweight)",
                    type = ChainNodeType.CUSTOM_FORMULA,
                    primaryValue = 2.0,
                    unit = "g",
                    formulaString = "body_weight * 2.0",
                    description = "Optimal protein to preserve lean muscle",
                    minValue = 0.5,
                    maxValue = 3.0,
                    step = 0.1
                )
            )
        )
    )

    /**
     * Executes the reactive cascade across all nodes in the chain in sequence.
     * Each node computes its output from the preceding node's result.
     */
    fun evaluateChain(chain: CalculationChain, scenario: ChainScenario = ChainScenario("Baseline")): List<ChainNode> {
        val updatedNodes = mutableListOf<ChainNode>()
        var runningValue = 0.0
        val nodeValuesMap = mutableMapOf<String, Double>()

        for ((index, node) in chain.nodes.withIndex()) {
            val effPrimary = when (node.type) {
                ChainNodeType.SOURCE_INPUT -> node.primaryValue * scenario.multiplier
                ChainNodeType.COMPOUND_GROWTH -> node.primaryValue + scenario.rateOffset
                else -> node.primaryValue
            }

            val nodeOutput = when (node.type) {
                ChainNodeType.SOURCE_INPUT -> {
                    effPrimary
                }
                ChainNodeType.SUBTRACT_AMOUNT -> {
                    runningValue - effPrimary
                }
                ChainNodeType.ADD_AMOUNT -> {
                    runningValue + effPrimary
                }
                ChainNodeType.MULTIPLY_VALUE -> {
                    runningValue * effPrimary
                }
                ChainNodeType.DIVIDE_VALUE -> {
                    if (effPrimary != 0.0) runningValue / effPrimary else 0.0
                }
                ChainNodeType.PERCENTAGE_DEDUCT -> {
                    runningValue * (1.0 - (effPrimary / 100.0))
                }
                ChainNodeType.PERCENTAGE_ADD -> {
                    runningValue * (1.0 + (effPrimary / 100.0))
                }
                ChainNodeType.PERCENTAGE_ALLOCATE -> {
                    runningValue * (effPrimary / 100.0)
                }
                ChainNodeType.COMPOUND_GROWTH -> {
                    // Future value of monthly SIP: P * [ (1+i)^n - 1 ] / i * (1+i)
                    val monthlyRate = (effPrimary / 100.0) / 12.0
                    val months = (node.secondaryValue.takeIf { it > 0.0 } ?: 15.0) * 12.0
                    val monthlyInvestment = runningValue
                    if (monthlyRate > 0.0 && monthlyInvestment > 0.0) {
                        monthlyInvestment * ((1.0 + monthlyRate).pow(months) - 1.0) / monthlyRate * (1.0 + monthlyRate)
                    } else {
                        monthlyInvestment * months
                    }
                }
                ChainNodeType.CUSTOM_FORMULA -> {
                    val formulaVars = nodeValuesMap.toMutableMap()
                    formulaVars["prev"] = runningValue
                    FormulaEvaluator.evaluate(node.formulaString.ifBlank { "prev" }, formulaVars)
                }
            }

            runningValue = nodeOutput
            nodeValuesMap[node.id] = nodeOutput

            updatedNodes.add(
                node.copy(
                    calculatedOutput = nodeOutput
                )
            )
        }

        return updatedNodes
    }
}
