package com.example.domain

import com.example.model.AppLanguage
import com.example.model.CalculatorMode

object LanguageStrings {

    fun getModeName(mode: CalculatorMode, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.ENGLISH -> when (mode) {
                CalculatorMode.STANDARD -> "Standard"
                CalculatorMode.GST_CALCULATOR -> "GST & Tax"
                CalculatorMode.CURRENCY_CONVERTER -> "Currency & Forex"
                CalculatorMode.SCIENTIFIC -> "Scientific"
                CalculatorMode.AGE_CALCULATOR -> "Age & Chrono"
                CalculatorMode.BMI_CALCULATOR -> "BMI Health"
                CalculatorMode.EMI_LOAN -> "Loan / EMI"
                CalculatorMode.PROGRAMMER -> "Programmer"
                CalculatorMode.UNIT_CONVERTER -> "Unit Converter"
                CalculatorMode.TIP_SPLIT -> "Tip & Split"
                CalculatorMode.ENGINEERING -> "Engineering"
                CalculatorMode.CUSTOM_BUILDER -> "Build a Calc"
                CalculatorMode.CALCULATION_CHAINS -> "Chains & Flow"
                CalculatorMode.AI_COPILOT -> "AI Math Copilot"
                CalculatorMode.WORKSHEET_TAPE -> "Worksheet & Tape"
            }
            AppLanguage.SPANISH -> when (mode) {
                CalculatorMode.STANDARD -> "Estándar"
                CalculatorMode.GST_CALCULATOR -> "IVA & Impuestos"
                CalculatorMode.CURRENCY_CONVERTER -> "Moneda & Divisas"
                CalculatorMode.SCIENTIFIC -> "Científica"
                CalculatorMode.AGE_CALCULATOR -> "Edad & Tiempo"
                CalculatorMode.BMI_CALCULATOR -> "IMC Salud"
                CalculatorMode.EMI_LOAN -> "Préstamo / Cuotas"
                CalculatorMode.PROGRAMMER -> "Programador"
                CalculatorMode.UNIT_CONVERTER -> "Conversor de Unidades"
                CalculatorMode.TIP_SPLIT -> "Propina & Cuenta"
                CalculatorMode.ENGINEERING -> "Ingeniería"
                CalculatorMode.CUSTOM_BUILDER -> "Creador IA"
                CalculatorMode.CALCULATION_CHAINS -> "Cadenas de Flujo"
                CalculatorMode.AI_COPILOT -> "Copiloto IA"
                CalculatorMode.WORKSHEET_TAPE -> "Hoja de Cálculo & Cinta"
            }
            AppLanguage.HINDI -> when (mode) {
                CalculatorMode.STANDARD -> "मानक कैलकुलेटर"
                CalculatorMode.GST_CALCULATOR -> "जीएसटी एवं कर"
                CalculatorMode.CURRENCY_CONVERTER -> "मुद्रा विनिमय"
                CalculatorMode.SCIENTIFIC -> "वैज्ञानिक"
                CalculatorMode.AGE_CALCULATOR -> "आयु एवं समय"
                CalculatorMode.BMI_CALCULATOR -> "बीएमआई स्वास्थ्य"
                CalculatorMode.EMI_LOAN -> "ऋण / ईएमआई"
                CalculatorMode.PROGRAMMER -> "प्रोग्रामर"
                CalculatorMode.UNIT_CONVERTER -> "इकाई परिवर्तक"
                CalculatorMode.TIP_SPLIT -> "टिप एवं विभाजन"
                CalculatorMode.ENGINEERING -> "इंजीनियरिंग"
                CalculatorMode.CUSTOM_BUILDER -> "कैलकुलेटर बनाएं"
                CalculatorMode.CALCULATION_CHAINS -> "गणना श्रृंखला"
                CalculatorMode.AI_COPILOT -> "एआई मैथ कोपायलट"
                CalculatorMode.WORKSHEET_TAPE -> "वर्कशीट एवं पेपर टेप"
            }
            AppLanguage.GUJARATI -> when (mode) {
                CalculatorMode.STANDARD -> "સ્ટાન્ડર્ડ કેલ્ક્યુલેટર"
                CalculatorMode.GST_CALCULATOR -> "જીએસટી અને ટેક્સ"
                CalculatorMode.CURRENCY_CONVERTER -> "ચલણ વિનિમય"
                CalculatorMode.SCIENTIFIC -> "વૈજ્ઞાનિક"
                CalculatorMode.AGE_CALCULATOR -> "ઉંમર અને સમય"
                CalculatorMode.BMI_CALCULATOR -> "બીએમઆઈ સ્વાસ્થ્ય"
                CalculatorMode.EMI_LOAN -> "લોન / ઈએમઆઈ"
                CalculatorMode.PROGRAMMER -> "પ્રોગ્રામર"
                CalculatorMode.UNIT_CONVERTER -> "એકમ કન્વર્ટર"
                CalculatorMode.TIP_SPLIT -> "ટિપ અને ભાગ"
                CalculatorMode.ENGINEERING -> "એન્જિનિયરિંગ"
                CalculatorMode.CUSTOM_BUILDER -> "કેલ્ક્યુલેટર બનાવો"
                CalculatorMode.CALCULATION_CHAINS -> "ચેઈન પ્રવાહ"
                CalculatorMode.AI_COPILOT -> "એઆઈ ગણિત સહાયક"
                CalculatorMode.WORKSHEET_TAPE -> "વર્કશીટ અને પેપર ટેપ"
            }
            AppLanguage.FRENCH -> when (mode) {
                CalculatorMode.STANDARD -> "Standard"
                CalculatorMode.GST_CALCULATOR -> "TVA & Taxes"
                CalculatorMode.CURRENCY_CONVERTER -> "Devises & Taux"
                CalculatorMode.SCIENTIFIC -> "Scientifique"
                CalculatorMode.AGE_CALCULATOR -> "Âge & Chrono"
                CalculatorMode.BMI_CALCULATOR -> "IMC Santé"
                CalculatorMode.EMI_LOAN -> "Prêt / Mensualité"
                CalculatorMode.PROGRAMMER -> "Programmeur"
                CalculatorMode.UNIT_CONVERTER -> "Convertisseur d'Unités"
                CalculatorMode.TIP_SPLIT -> "Pourboire & Partage"
                CalculatorMode.ENGINEERING -> "Ingénierie"
                CalculatorMode.CUSTOM_BUILDER -> "Créer Calculatrice"
                CalculatorMode.CALCULATION_CHAINS -> "Chaînes de Calcul"
                CalculatorMode.AI_COPILOT -> "Copilote IA"
                CalculatorMode.WORKSHEET_TAPE -> "Feuille & Ruban Papier"
            }
            AppLanguage.GERMAN -> when (mode) {
                CalculatorMode.STANDARD -> "Standard"
                CalculatorMode.GST_CALCULATOR -> "MwSt. & Steuern"
                CalculatorMode.CURRENCY_CONVERTER -> "Währungsumrechner"
                CalculatorMode.SCIENTIFIC -> "Wissenschaftlich"
                CalculatorMode.AGE_CALCULATOR -> "Alter & Zeit"
                CalculatorMode.BMI_CALCULATOR -> "BMI Gesundheit"
                CalculatorMode.EMI_LOAN -> "Kredit & Raten"
                CalculatorMode.PROGRAMMER -> "Programmierer"
                CalculatorMode.UNIT_CONVERTER -> "Einheitenumrechner"
                CalculatorMode.TIP_SPLIT -> "Trinkgeld & Teilen"
                CalculatorMode.ENGINEERING -> "Ingenieurwesen"
                CalculatorMode.CUSTOM_BUILDER -> "Rechner Baukasten"
                CalculatorMode.CALCULATION_CHAINS -> "Kettenrechnung"
                CalculatorMode.AI_COPILOT -> "KI Mathe-Copilot"
                CalculatorMode.WORKSHEET_TAPE -> "Arbeitsblatt & Streifen"
            }
            AppLanguage.JAPANESE -> when (mode) {
                CalculatorMode.STANDARD -> "標準電卓"
                CalculatorMode.GST_CALCULATOR -> "消費税・GST"
                CalculatorMode.CURRENCY_CONVERTER -> "為替レート換算"
                CalculatorMode.SCIENTIFIC -> "関数電卓"
                CalculatorMode.AGE_CALCULATOR -> "年齢・時間計算"
                CalculatorMode.BMI_CALCULATOR -> "BMI 健康計算"
                CalculatorMode.EMI_LOAN -> "ローン・返済計算"
                CalculatorMode.PROGRAMMER -> "プログラマー電卓"
                CalculatorMode.UNIT_CONVERTER -> "単位変換"
                CalculatorMode.TIP_SPLIT -> "割り勘・チップ"
                CalculatorMode.ENGINEERING -> "工学・定数計算"
                CalculatorMode.CUSTOM_BUILDER -> "AI電卓作成"
                CalculatorMode.CALCULATION_CHAINS -> "連動フロー計算"
                CalculatorMode.AI_COPILOT -> "AI数学コパイロット"
                CalculatorMode.WORKSHEET_TAPE -> "ワークシート・計算テープ"
            }
            AppLanguage.CHINESE -> when (mode) {
                CalculatorMode.STANDARD -> "标准计算"
                CalculatorMode.GST_CALCULATOR -> "消费税与增值税"
                CalculatorMode.CURRENCY_CONVERTER -> "汇率与货币"
                CalculatorMode.SCIENTIFIC -> "科学计算器"
                CalculatorMode.AGE_CALCULATOR -> "年龄与时间"
                CalculatorMode.BMI_CALCULATOR -> "BMI 健康指数"
                CalculatorMode.EMI_LOAN -> "房贷与分期"
                CalculatorMode.PROGRAMMER -> "程序员计算"
                CalculatorMode.UNIT_CONVERTER -> "单位换算器"
                CalculatorMode.TIP_SPLIT -> "小费与AA制"
                CalculatorMode.ENGINEERING -> "工程物理"
                CalculatorMode.CUSTOM_BUILDER -> "AI定制计算器"
                CalculatorMode.CALCULATION_CHAINS -> "级联链式计算"
                CalculatorMode.AI_COPILOT -> "AI数学副驾"
                CalculatorMode.WORKSHEET_TAPE -> "工作表与纸带计算"
            }
            AppLanguage.ARABIC -> when (mode) {
                CalculatorMode.STANDARD -> "قياسي"
                CalculatorMode.GST_CALCULATOR -> "الضريبة المضافة"
                CalculatorMode.CURRENCY_CONVERTER -> "أسعار العملات"
                CalculatorMode.SCIENTIFIC -> "حاسبة علمية"
                CalculatorMode.AGE_CALCULATOR -> "العمر والوقت"
                CalculatorMode.BMI_CALCULATOR -> "مؤشر كتلة الجسم"
                CalculatorMode.EMI_LOAN -> "القروض والتمويل"
                CalculatorMode.PROGRAMMER -> "حاسبة المبرمج"
                CalculatorMode.UNIT_CONVERTER -> "محول الوحدات"
                CalculatorMode.TIP_SPLIT -> "الإكرامية والتقسيم"
                CalculatorMode.ENGINEERING -> "حاسبة الهندسة"
                CalculatorMode.CUSTOM_BUILDER -> "صانع الحاسبات الذكي"
                CalculatorMode.CALCULATION_CHAINS -> "سلاسل الحسابات"
                CalculatorMode.AI_COPILOT -> "مساعد الذكاء الاصطناعي"
                CalculatorMode.WORKSHEET_TAPE -> "ورقة العمل والشريط الورقي"
            }
            AppLanguage.PORTUGUESE -> when (mode) {
                CalculatorMode.STANDARD -> "Padrão"
                CalculatorMode.GST_CALCULATOR -> "IVA & Impostos"
                CalculatorMode.CURRENCY_CONVERTER -> "Câmbio & Moedas"
                CalculatorMode.SCIENTIFIC -> "Científica"
                CalculatorMode.AGE_CALCULATOR -> "Idade & Tempo"
                CalculatorMode.BMI_CALCULATOR -> "IMC Saúde"
                CalculatorMode.EMI_LOAN -> "Empréstimo / Financiamento"
                CalculatorMode.PROGRAMMER -> "Programador"
                CalculatorMode.UNIT_CONVERTER -> "Conversor de Unidades"
                CalculatorMode.TIP_SPLIT -> "Gorjeta & Divisão"
                CalculatorMode.ENGINEERING -> "Engenharia"
                CalculatorMode.CUSTOM_BUILDER -> "Criador IA"
                CalculatorMode.CALCULATION_CHAINS -> "Cadeias de Cálculo"
                CalculatorMode.AI_COPILOT -> "Copiloto IA"
                CalculatorMode.WORKSHEET_TAPE -> "Planilha & Fita de Papel"
            }
            AppLanguage.RUSSIAN -> when (mode) {
                CalculatorMode.STANDARD -> "Стандартный"
                CalculatorMode.GST_CALCULATOR -> "НДС и налоги"
                CalculatorMode.CURRENCY_CONVERTER -> "Курсы валют"
                CalculatorMode.SCIENTIFIC -> "Инженерный"
                CalculatorMode.AGE_CALCULATOR -> "Возраст и время"
                CalculatorMode.BMI_CALCULATOR -> "ИМТ Здоровье"
                CalculatorMode.EMI_LOAN -> "Кредит / Рассрочка"
                CalculatorMode.PROGRAMMER -> "Программист"
                CalculatorMode.UNIT_CONVERTER -> "Конвертер величин"
                CalculatorMode.TIP_SPLIT -> "Чаевые и счёт"
                CalculatorMode.ENGINEERING -> "Инженерия"
                CalculatorMode.CUSTOM_BUILDER -> "Конструктор калькуляторов"
                CalculatorMode.CALCULATION_CHAINS -> "Каскадные вычисления"
                CalculatorMode.AI_COPILOT -> "ИИ Копилот"
                CalculatorMode.WORKSHEET_TAPE -> "Таблица и бумажная лента"
            }
            AppLanguage.ITALIAN -> when (mode) {
                CalculatorMode.STANDARD -> "Standard"
                CalculatorMode.GST_CALCULATOR -> "IVA & Imposte"
                CalculatorMode.CURRENCY_CONVERTER -> "Valute & Cambio"
                CalculatorMode.SCIENTIFIC -> "Scientifica"
                CalculatorMode.AGE_CALCULATOR -> "Età & Tempo"
                CalculatorMode.BMI_CALCULATOR -> "IMC Salute"
                CalculatorMode.EMI_LOAN -> "Prestito / Rate"
                CalculatorMode.PROGRAMMER -> "Programmatore"
                CalculatorMode.UNIT_CONVERTER -> "Convertitore di Unità"
                CalculatorMode.TIP_SPLIT -> "Mancia & Divisione"
                CalculatorMode.ENGINEERING -> "Ingegneria"
                CalculatorMode.CUSTOM_BUILDER -> "Crea Calcolatrice"
                CalculatorMode.CALCULATION_CHAINS -> "Catene di Calcolo"
                CalculatorMode.AI_COPILOT -> "Copilota IA"
                CalculatorMode.WORKSHEET_TAPE -> "Foglio & Nastro di Carta"
            }
            AppLanguage.INDONESIAN -> when (mode) {
                CalculatorMode.STANDARD -> "Standar"
                CalculatorMode.GST_CALCULATOR -> "PPN & Pajak"
                CalculatorMode.CURRENCY_CONVERTER -> "Kurs & Valuta"
                CalculatorMode.SCIENTIFIC -> "Ilmiah"
                CalculatorMode.AGE_CALCULATOR -> "Usia & Waktu"
                CalculatorMode.BMI_CALCULATOR -> "BMI Kesehatan"
                CalculatorMode.EMI_LOAN -> "Pinjaman & Cicilan"
                CalculatorMode.PROGRAMMER -> "Programmer"
                CalculatorMode.UNIT_CONVERTER -> "Konversi Satuan"
                CalculatorMode.TIP_SPLIT -> "Tip & Patungan"
                CalculatorMode.ENGINEERING -> "Teknik"
                CalculatorMode.CUSTOM_BUILDER -> "Pembuat Kalkulator"
                CalculatorMode.CALCULATION_CHAINS -> "Rantai Perhitungan"
                CalculatorMode.AI_COPILOT -> "Kopilot AI"
                CalculatorMode.WORKSHEET_TAPE -> "Lembar Kerja & Pita Kertas"
            }
            AppLanguage.KOREAN -> when (mode) {
                CalculatorMode.STANDARD -> "표준 계산기"
                CalculatorMode.GST_CALCULATOR -> "부가가치세 (부가세)"
                CalculatorMode.CURRENCY_CONVERTER -> "환율 계산기"
                CalculatorMode.SCIENTIFIC -> "공학용 계산기"
                CalculatorMode.AGE_CALCULATOR -> "만 나이 / D-Day"
                CalculatorMode.BMI_CALCULATOR -> "BMI 비만도 계산"
                CalculatorMode.EMI_LOAN -> "대출 이자 / 할부"
                CalculatorMode.PROGRAMMER -> "프로그래머 계산기"
                CalculatorMode.UNIT_CONVERTER -> "단위 변환기"
                CalculatorMode.TIP_SPLIT -> "더치페이 / 팁"
                CalculatorMode.ENGINEERING -> "물리 공학 계산"
                CalculatorMode.CUSTOM_BUILDER -> "AI 맞춤 계산기 생성"
                CalculatorMode.CALCULATION_CHAINS -> "연쇄 반응 계산 흐름"
                CalculatorMode.AI_COPILOT -> "AI 수학 코파일럿"
                CalculatorMode.WORKSHEET_TAPE -> "워크시트 / 계산 테이프"
            }
            AppLanguage.TURKISH -> when (mode) {
                CalculatorMode.STANDARD -> "Standart"
                CalculatorMode.GST_CALCULATOR -> "KDV & Vergi"
                CalculatorMode.CURRENCY_CONVERTER -> "Döviz Kurları"
                CalculatorMode.SCIENTIFIC -> "Bilimsel"
                CalculatorMode.AGE_CALCULATOR -> "Yaş & Zaman"
                CalculatorMode.BMI_CALCULATOR -> "VKİ Sağlık"
                CalculatorMode.EMI_LOAN -> "Kredi & Taksit"
                CalculatorMode.PROGRAMMER -> "Programcı"
                CalculatorMode.UNIT_CONVERTER -> "Birim Dönüştürücü"
                CalculatorMode.TIP_SPLIT -> "Bahşiş & Hesap"
                CalculatorMode.ENGINEERING -> "Mühendislik"
                CalculatorMode.CUSTOM_BUILDER -> "Hesap Makinesi Oluştur"
                CalculatorMode.CALCULATION_CHAINS -> "Zincir Hesaplama"
                CalculatorMode.AI_COPILOT -> "Yapay Zeka Yardımcısı"
                CalculatorMode.WORKSHEET_TAPE -> "Çalışma Sayfası & Hesap Şeridi"
            }
        }
    }

    // --- GST Screen Texts ---
    fun gstAddText(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "IVA+ (Añadir)"
        AppLanguage.HINDI -> "जीएसटी+ (जोड़ें)"
        AppLanguage.GUJARATI -> "જીએસટી+ (ઉમેરો)"
        AppLanguage.FRENCH -> "TVA+ (Ajouter)"
        AppLanguage.GERMAN -> "MwSt+ (Zufügen)"
        AppLanguage.JAPANESE -> "税込 (加算)"
        AppLanguage.CHINESE -> "加税+ (含税)"
        AppLanguage.ARABIC -> "ضريبة+ (إضافة)"
        AppLanguage.PORTUGUESE -> "IVA+ (Adicionar)"
        AppLanguage.RUSSIAN -> "НДС+ (Добавить)"
        AppLanguage.ITALIAN -> "IVA+ (Aggiungi)"
        AppLanguage.INDONESIAN -> "PPN+ (Tambah)"
        AppLanguage.KOREAN -> "부가세+ (과세)"
        AppLanguage.TURKISH -> "KDV+ (Ekle)"
        else -> "GST+ (Add)"
    }

    fun gstExtractText(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "IVA− (Extraer)"
        AppLanguage.HINDI -> "जीएसटी− (घटाएं)"
        AppLanguage.GUJARATI -> "જીએસટી− (બાદ કરો)"
        AppLanguage.FRENCH -> "TVA− (Extraire)"
        AppLanguage.GERMAN -> "MwSt− (Abziehen)"
        AppLanguage.JAPANESE -> "税抜 (抽出)"
        AppLanguage.CHINESE -> "去税− (提取)"
        AppLanguage.ARABIC -> "ضريبة− (استخراج)"
        AppLanguage.PORTUGUESE -> "IVA− (Extrair)"
        AppLanguage.RUSSIAN -> "НДС− (Извлечь)"
        AppLanguage.ITALIAN -> "IVA− (Scorporo)"
        AppLanguage.INDONESIAN -> "PPN− (Kurang)"
        AppLanguage.KOREAN -> "부가세− (면세/공제)"
        AppLanguage.TURKISH -> "KDV− (Çıkar)"
        else -> "GST− (Extract)"
    }

    fun gstBaseAmountLabel(rate: String, lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "IMPORTE BASE (ANTES DE $rate IVA)"
        AppLanguage.HINDI -> "मूल राशि ($rate जीएसटी से पहले)"
        AppLanguage.GUJARATI -> "મૂળ રકમ ($rate જીએસટી પહેલા)"
        AppLanguage.FRENCH -> "MONTANT DE BASE (AVANT $rate TVA)"
        AppLanguage.GERMAN -> "NETTOBETRAG (VOR $rate MWST)"
        AppLanguage.JAPANESE -> "税抜金額 (消費税 $rate 前)"
        AppLanguage.CHINESE -> "不含税基数 (计入 $rate 税前)"
        AppLanguage.ARABIC -> "المبلغ الأساسي (قبل $rate الضريبة)"
        AppLanguage.PORTUGUESE -> "VALOR BASE (ANTES DE $rate IVA)"
        AppLanguage.RUSSIAN -> "СУММА БЕЗ НДС (ДО $rate%)"
        AppLanguage.ITALIAN -> "IMPORTO BASE (PRIMA DEL $rate IVA)"
        AppLanguage.INDONESIAN -> "NILAI DASAR (SEBELUM PPN $rate)"
        AppLanguage.KOREAN -> "공급가액 (부가세 $rate 적용 전)"
        AppLanguage.TURKISH -> "MATRAH TUTARI (%$rate KDV ÖNCESİ)"
        else -> "BASE AMOUNT (BEFORE $rate GST)"
    }

    fun gstGrossAmountLabel(rate: String, lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "IMPORTE TOTAL (CON $rate IVA)"
        AppLanguage.HINDI -> "कुल राशि ($rate जीएसटी सहित)"
        AppLanguage.GUJARATI -> "કુલ રકમ ($rate જીએસટી સાથે)"
        AppLanguage.FRENCH -> "MONTANT TOTAL (TTC $rate)"
        AppLanguage.GERMAN -> "BRUTTOBETRAG (INKL. $rate MWST)"
        AppLanguage.JAPANESE -> "税込総額 ($rate 込)"
        AppLanguage.CHINESE -> "含税总额 (含 $rate 税款)"
        AppLanguage.ARABIC -> "المبلغ الإجمالي (شامل $rate ضريبة)"
        AppLanguage.PORTUGUESE -> "VALOR BRUTO (COM $rate IVA)"
        AppLanguage.RUSSIAN -> "ИТОГО С НДС (ВКЛЮЧАЯ $rate%)"
        AppLanguage.ITALIAN -> "TOTALE LORDO (INCL. $rate IVA)"
        AppLanguage.INDONESIAN -> "TOTAL BRUTO (TERMASUK PPN $rate)"
        AppLanguage.KOREAN -> "합계금액 (부가세 $rate 포함)"
        AppLanguage.TURKISH -> "TOPLAM BRÜT (DAHİL %$rate KDV)"
        else -> "GROSS AMOUNT (INCL $rate GST)"
    }

    fun netAmount(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "Importe Neto"
        AppLanguage.HINDI -> "शुद्ध राशि"
        AppLanguage.GUJARATI -> "ચોખ્ખી રકમ"
        AppLanguage.FRENCH -> "Montant Net"
        AppLanguage.GERMAN -> "Nettobetrag"
        AppLanguage.JAPANESE -> "税抜金額"
        AppLanguage.CHINESE -> "净额"
        AppLanguage.ARABIC -> "المبلغ الصافي"
        AppLanguage.PORTUGUESE -> "Valor Líquido"
        AppLanguage.RUSSIAN -> "Чистая сумма"
        AppLanguage.ITALIAN -> "Importo Netto"
        AppLanguage.INDONESIAN -> "Nilai Bersih"
        AppLanguage.KOREAN -> "공급가액"
        AppLanguage.TURKISH -> "Net Tutar"
        else -> "Net Amount"
    }

    fun totalTax(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "Impuesto Total"
        AppLanguage.HINDI -> "कुल कर"
        AppLanguage.GUJARATI -> "કુલ ટેક્સ"
        AppLanguage.FRENCH -> "Taxe Totale"
        AppLanguage.GERMAN -> "Gesamtsteuer"
        AppLanguage.JAPANESE -> "税額合計"
        AppLanguage.CHINESE -> "税额合计"
        AppLanguage.ARABIC -> "إجمالي الضريبة"
        AppLanguage.PORTUGUESE -> "Imposto Total"
        AppLanguage.RUSSIAN -> "Всего налог"
        AppLanguage.ITALIAN -> "Totale Imposte"
        AppLanguage.INDONESIAN -> "Total Pajak"
        AppLanguage.KOREAN -> "총 세액"
        AppLanguage.TURKISH -> "Toplam Vergi"
        else -> "Total Tax"
    }

    fun totalGross(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "TOTAL BRUTO"
        AppLanguage.HINDI -> "सकल कुल योग"
        AppLanguage.GUJARATI -> "કુલ ગ્રોસ રકમ"
        AppLanguage.FRENCH -> "TOTAL TTC"
        AppLanguage.GERMAN -> "GESAMTBRUTTO"
        AppLanguage.JAPANESE -> "総支払額"
        AppLanguage.CHINESE -> "应付总额"
        AppLanguage.ARABIC -> "الإجمالي الكلي"
        AppLanguage.PORTUGUESE -> "TOTAL BRUTO"
        AppLanguage.RUSSIAN -> "ОБЩАЯ СУММА"
        AppLanguage.ITALIAN -> "TOTALE LORDO"
        AppLanguage.INDONESIAN -> "TOTAL AKHIR"
        AppLanguage.KOREAN -> "최종 결제금액"
        AppLanguage.TURKISH -> "GENEL TOPLAM"
        else -> "TOTAL GROSS"
    }

    fun rateSet(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "CONFIG. TASAS"
        AppLanguage.HINDI -> "दरें सेट करें"
        AppLanguage.GUJARATI -> "દર સેટ કરો"
        AppLanguage.FRENCH -> "RÉGLER TAUX"
        AppLanguage.GERMAN -> "STEUERSATZ"
        AppLanguage.JAPANESE -> "税率設定"
        AppLanguage.CHINESE -> "设置税率"
        AppLanguage.ARABIC -> "تعديل النسب"
        AppLanguage.PORTUGUESE -> "AJUSTAR TAXAS"
        AppLanguage.RUSSIAN -> "НАСТРОЙКА СТАВОК"
        AppLanguage.ITALIAN -> "IMPOSTA TASSI"
        AppLanguage.INDONESIAN -> "ATUR TARIF"
        AppLanguage.KOREAN -> "세율 설정"
        AppLanguage.TURKISH -> "ORAN AYARLA"
        else -> "RATE SET"
    }

    fun rateSelectionHeader(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "── SELECCIÓN DE TASA DE IVA ──"
        AppLanguage.HINDI -> "── जीएसटी दर चयन ──"
        AppLanguage.GUJARATI -> "── જીએસટી દર પસંદગી ──"
        AppLanguage.FRENCH -> "── SÉLECTION DU TAUX TVA ──"
        AppLanguage.GERMAN -> "── STEUERSATZ AUSWAHL ──"
        AppLanguage.JAPANESE -> "── 消費税率選択 ──"
        AppLanguage.CHINESE -> "── 税率快捷选择 ──"
        AppLanguage.ARABIC -> "── اختيار نسبة الضريبة ──"
        AppLanguage.PORTUGUESE -> "── SELEÇÃO DE TAXA IVA ──"
        AppLanguage.RUSSIAN -> "── ВЫБОР СТАВКИ НАЛОГА ──"
        AppLanguage.ITALIAN -> "── SELEZIONE ALIQUOTA IVA ──"
        AppLanguage.INDONESIAN -> "── PILIHAN TARIF PPN ──"
        AppLanguage.KOREAN -> "── 부가세율 선택 ──"
        AppLanguage.TURKISH -> "── KDV ORANI SEÇİMİ ──"
        else -> "── GST RATE SELECTION ──"
    }

    fun grandTotal(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "Gran Total"
        AppLanguage.HINDI -> "भव्य कुल (GT)"
        AppLanguage.GUJARATI -> "ગ્રાન્ડ ટોટલ (GT)"
        AppLanguage.FRENCH -> "Grand Total"
        AppLanguage.GERMAN -> "Gesamtsumme"
        AppLanguage.JAPANESE -> "総合計 (GT)"
        AppLanguage.CHINESE -> "总累计 (GT)"
        AppLanguage.ARABIC -> "المجموع الكلي"
        AppLanguage.PORTUGUESE -> "Grande Total"
        AppLanguage.RUSSIAN -> "Общий итог"
        AppLanguage.ITALIAN -> "Totale Generale"
        AppLanguage.INDONESIAN -> "Grand Total"
        AppLanguage.KOREAN -> "누적 총계 (GT)"
        AppLanguage.TURKISH -> "Genel Toplam (GT)"
        else -> "Grand Total (GT)"
    }

    fun clearGt(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "Borrar GT"
        AppLanguage.HINDI -> "जीटी साफ़ करें"
        AppLanguage.GUJARATI -> "જીટી સાફ કરો"
        AppLanguage.FRENCH -> "Effacer GT"
        AppLanguage.GERMAN -> "GT Löschen"
        AppLanguage.JAPANESE -> "GTクリア"
        AppLanguage.CHINESE -> "清除 GT"
        AppLanguage.ARABIC -> "مسح الإجمالي"
        AppLanguage.PORTUGUESE -> "Limpar GT"
        AppLanguage.RUSSIAN -> "Сбросить GT"
        AppLanguage.ITALIAN -> "Cancella GT"
        AppLanguage.INDONESIAN -> "Hapus GT"
        AppLanguage.KOREAN -> "GT 초기화"
        AppLanguage.TURKISH -> "GT Temizle"
        else -> "Clear GT"
    }

    // --- Settings & UI Texts ---
    fun settingsTitle(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "Ajustes & Personalización"
        AppLanguage.HINDI -> "सेटिंग्स और प्रकटन"
        AppLanguage.GUJARATI -> "સેટિંગ્સ અને દેખાવ"
        AppLanguage.FRENCH -> "Paramètres & Apparence"
        AppLanguage.GERMAN -> "Einstellungen & Design"
        AppLanguage.JAPANESE -> "設定とカスタマイズ"
        AppLanguage.CHINESE -> "设置与个性化"
        AppLanguage.ARABIC -> "الإعدادات والمظهر"
        AppLanguage.PORTUGUESE -> "Definições & Aparência"
        AppLanguage.RUSSIAN -> "Настройки и тема"
        AppLanguage.ITALIAN -> "Impostazioni e Aspetto"
        AppLanguage.INDONESIAN -> "Pengaturan & Tampilan"
        AppLanguage.KOREAN -> "설정 및 맞춤 구성"
        AppLanguage.TURKISH -> "Ayarlar & Görünüm"
        else -> "Settings & Customization"
    }

    fun tabThemes(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "Temas"
        AppLanguage.HINDI -> "थीम्स"
        AppLanguage.GUJARATI -> "થીમ્સ"
        AppLanguage.FRENCH -> "Thèmes"
        AppLanguage.GERMAN -> "Designs"
        AppLanguage.JAPANESE -> "テーマ"
        AppLanguage.CHINESE -> "主题"
        AppLanguage.ARABIC -> "السمات"
        AppLanguage.PORTUGUESE -> "Temas"
        AppLanguage.RUSSIAN -> "Темы"
        AppLanguage.ITALIAN -> "Temi"
        AppLanguage.INDONESIAN -> "Tema"
        AppLanguage.KOREAN -> "테마"
        AppLanguage.TURKISH -> "Temalar"
        else -> "Themes"
    }

    fun tabDisplay(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "Pantalla"
        AppLanguage.HINDI -> "डिस्प्ले"
        AppLanguage.GUJARATI -> "ડિસ્પ્લે"
        AppLanguage.FRENCH -> "Affichage"
        AppLanguage.GERMAN -> "Anzeige"
        AppLanguage.JAPANESE -> "表示"
        AppLanguage.CHINESE -> "显示"
        AppLanguage.ARABIC -> "الشاشة"
        AppLanguage.PORTUGUESE -> "Ecrã"
        AppLanguage.RUSSIAN -> "Экран"
        AppLanguage.ITALIAN -> "Display"
        AppLanguage.INDONESIAN -> "Tampilan"
        AppLanguage.KOREAN -> "디스플레이"
        AppLanguage.TURKISH -> "Ekran"
        else -> "Display"
    }

    fun tabLanguage(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "Idioma"
        AppLanguage.HINDI -> "भाषा"
        AppLanguage.GUJARATI -> "ભાષા"
        AppLanguage.FRENCH -> "Langue"
        AppLanguage.GERMAN -> "Sprache"
        AppLanguage.JAPANESE -> "言語"
        AppLanguage.CHINESE -> "语言"
        AppLanguage.ARABIC -> "اللغة"
        AppLanguage.PORTUGUESE -> "Idioma"
        AppLanguage.RUSSIAN -> "Язык"
        AppLanguage.ITALIAN -> "Lingua"
        AppLanguage.INDONESIAN -> "Bahasa"
        AppLanguage.KOREAN -> "언어"
        AppLanguage.TURKISH -> "Dil"
        else -> "Language"
    }

    fun tabHaptics(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "Sonido"
        AppLanguage.HINDI -> "ध्वनि/कंपन"
        AppLanguage.GUJARATI -> "અવાજ/કંપન"
        AppLanguage.FRENCH -> "Sons"
        AppLanguage.GERMAN -> "Audio"
        AppLanguage.JAPANESE -> "効果音"
        AppLanguage.CHINESE -> "声音震动"
        AppLanguage.ARABIC -> "الصوت"
        AppLanguage.PORTUGUESE -> "Áudio"
        AppLanguage.RUSSIAN -> "Звук"
        AppLanguage.ITALIAN -> "Suono"
        AppLanguage.INDONESIAN -> "Suara"
        AppLanguage.KOREAN -> "소리/진동"
        AppLanguage.TURKISH -> "Ses"
        else -> "Sound"
    }

    fun tabAbout(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "Acerca de"
        AppLanguage.HINDI -> "के बारे में"
        AppLanguage.GUJARATI -> "વિશે"
        AppLanguage.FRENCH -> "À propos"
        AppLanguage.GERMAN -> "Über"
        AppLanguage.JAPANESE -> "情報"
        AppLanguage.CHINESE -> "关于"
        AppLanguage.ARABIC -> "حول"
        AppLanguage.PORTUGUESE -> "Sobre"
        AppLanguage.RUSSIAN -> "О приложении"
        AppLanguage.ITALIAN -> "Info"
        AppLanguage.INDONESIAN -> "Tentang"
        AppLanguage.KOREAN -> "정보"
        AppLanguage.TURKISH -> "Hakkında"
        else -> "About"
    }

    fun done(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "Listo"
        AppLanguage.HINDI -> "संपन्न"
        AppLanguage.GUJARATI -> "પૂર્ણ"
        AppLanguage.FRENCH -> "Terminé"
        AppLanguage.GERMAN -> "Fertig"
        AppLanguage.JAPANESE -> "完了"
        AppLanguage.CHINESE -> "完成"
        AppLanguage.ARABIC -> "تم"
        AppLanguage.PORTUGUESE -> "Concluído"
        AppLanguage.RUSSIAN -> "Готово"
        AppLanguage.ITALIAN -> "Fatto"
        AppLanguage.INDONESIAN -> "Selesai"
        AppLanguage.KOREAN -> "완료"
        AppLanguage.TURKISH -> "Tamam"
        else -> "Done"
    }

    fun chooseLanguage(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "Seleccionar Idioma"
        AppLanguage.HINDI -> "भाषा चुनें"
        AppLanguage.GUJARATI -> "ભાષા પસંદ કરો"
        AppLanguage.FRENCH -> "Choisir la Langue"
        AppLanguage.GERMAN -> "Sprache Wählen"
        AppLanguage.JAPANESE -> "言語を選択"
        AppLanguage.CHINESE -> "选择语言"
        AppLanguage.ARABIC -> "اختر اللغة"
        AppLanguage.PORTUGUESE -> "Escolher Idioma"
        AppLanguage.RUSSIAN -> "Выбрать язык"
        AppLanguage.ITALIAN -> "Scegli Lingua"
        AppLanguage.INDONESIAN -> "Pilih Bahasa"
        AppLanguage.KOREAN -> "언어 선택"
        AppLanguage.TURKISH -> "Dil Seçin"
        else -> "Choose Language"
    }

    fun modeStandard(lang: AppLanguage): String = getModeName(CalculatorMode.STANDARD, lang)
    fun modeGst(lang: AppLanguage): String = getModeName(CalculatorMode.GST_CALCULATOR, lang)
    fun modeScientific(lang: AppLanguage): String = getModeName(CalculatorMode.SCIENTIFIC, lang)
    fun modeMore(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "Más"
        AppLanguage.HINDI -> "अधिक"
        AppLanguage.GUJARATI -> "વધુ"
        AppLanguage.FRENCH -> "Plus"
        AppLanguage.GERMAN -> "Mehr"
        AppLanguage.JAPANESE -> "その他"
        AppLanguage.CHINESE -> "更多"
        AppLanguage.ARABIC -> "المزيد"
        AppLanguage.PORTUGUESE -> "Mais"
        AppLanguage.RUSSIAN -> "Ещё"
        AppLanguage.ITALIAN -> "Altro"
        AppLanguage.INDONESIAN -> "Lainnya"
        AppLanguage.KOREAN -> "더보기"
        AppLanguage.TURKISH -> "Daha Fazla"
        else -> "More"
    }

    fun close(lang: AppLanguage): String = when (lang) {
        AppLanguage.SPANISH -> "Cerrar"
        AppLanguage.HINDI -> "बंद करें"
        AppLanguage.GUJARATI -> "બંધ કરો"
        AppLanguage.FRENCH -> "Fermer"
        AppLanguage.GERMAN -> "Schließen"
        AppLanguage.JAPANESE -> "閉じる"
        AppLanguage.CHINESE -> "关闭"
        AppLanguage.ARABIC -> "إغلاق"
        AppLanguage.PORTUGUESE -> "Fechar"
        AppLanguage.RUSSIAN -> "Закрыть"
        AppLanguage.ITALIAN -> "Chiudi"
        AppLanguage.INDONESIAN -> "Tutup"
        AppLanguage.KOREAN -> "닫기"
        AppLanguage.TURKISH -> "Kapat"
        else -> "Close"
    }
}
