package com.example.ui.theme

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.example.model.ButtonShapeType
import com.example.model.DisplayFontType
import com.example.model.PressAnimationType
import com.example.model.ThemeId
import com.example.model.ThemePalette

object CalculatorThemes {

    val Cyberpunk = ThemePalette(
        id = ThemeId.CYBERPUNK,
        name = "Cyberpunk 2099",
        subtitle = "Electric neon, cyan & magenta glow",
        category = "Futuristic",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF070B19), Color(0xFF0D1527), Color(0xFF080C1B))
        ),
        backgroundColor = Color(0xFF070B19),
        surfaceColor = Color(0xFF0D1527),
        cardBackground = Color(0xFF101C36),
        screenBackground = Color(0xFF080E1E),
        screenBorderColor = Color(0xFF00F0FF),
        screenTextColor = Color(0xFF00F0FF),
        screenExpressionColor = Color(0xFF88A0C8),
        screenPreviewColor = Color(0xFFFF007F),
        cursorColor = Color(0xFF00F0FF),
        displayFont = DisplayFontType.MONOSPACE,
        hasScanlines = false,
        numberButtonBg = Color(0xFF111E38),
        numberButtonText = Color(0xFFE2F1FF),
        numberButtonBorder = Color(0x3300F0FF),
        operatorButtonBg = Color(0xFF261033),
        operatorButtonText = Color(0xFFFF007F),
        operatorButtonBorder = Color(0x66FF007F),
        functionButtonBg = Color(0xFF0E2738),
        functionButtonText = Color(0xFFFFD600),
        functionButtonBorder = Color(0x44FFD600),
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFF00F0FF), Color(0xFFFF007F))
        ),
        equalsButtonText = Color(0xFF070B19),
        accentColor = Color(0xFF00F0FF),
        secondaryAccent = Color(0xFFFF007F),
        glowColor = Color(0x6600F0FF),
        shapeType = ButtonShapeType.ROUNDED_SQUARE,
        cornerRadiusDp = 12.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 4.dp,
        pressAnimation = PressAnimationType.NEON_GLOW,
        statusBarDarkIcons = false
    )

    val Synthwave = ThemePalette(
        id = ThemeId.SYNTHWAVE,
        name = "Synthwave 80s",
        subtitle = "Retro arcade sunset & hot pink",
        category = "Retro",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF19092B), Color(0xFF2E0D49), Color(0xFF16002A))
        ),
        backgroundColor = Color(0xFF19092B),
        surfaceColor = Color(0xFF2B0E44),
        cardBackground = Color(0xFF381359),
        screenBackground = Color(0xFF200735),
        screenBorderColor = Color(0xFFFF3377),
        screenTextColor = Color(0xFFFFE66D),
        screenExpressionColor = Color(0xFFD4A5FF),
        screenPreviewColor = Color(0xFF00F5D4),
        cursorColor = Color(0xFFFF3377),
        displayFont = DisplayFontType.DIGITAL_LCD,
        hasScanlines = false,
        numberButtonBg = Color(0xFF351254),
        numberButtonText = Color(0xFFFFF0F5),
        numberButtonBorder = Color(0x44FF7597),
        operatorButtonBg = Color(0xFFFF2A6D),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color.Transparent,
        functionButtonBg = Color(0xFF05D9E8),
        functionButtonText = Color(0xFF01012B),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFFFF2A6D), Color(0xFFFF9F1C))
        ),
        equalsButtonText = Color(0xFFFFFFFF),
        accentColor = Color(0xFFFF2A6D),
        secondaryAccent = Color(0xFF05D9E8),
        glowColor = Color(0x66FF2A6D),
        shapeType = ButtonShapeType.ROUNDED_SQUARE,
        cornerRadiusDp = 14.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 4.dp,
        pressAnimation = PressAnimationType.BOUNCE,
        statusBarDarkIcons = false
    )

    val NeoBrutalism = ThemePalette(
        id = ThemeId.NEO_BRUTALISM,
        name = "Neo-Brutalism",
        subtitle = "Bold pop colors, thick borders & hard shadows",
        category = "Modern Art",
        isDark = false,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFFFFFBEB), Color(0xFFFEF3C7))
        ),
        backgroundColor = Color(0xFFFFFBEB),
        surfaceColor = Color(0xFFFEF08A),
        cardBackground = Color(0xFFFFFFFF),
        screenBackground = Color(0xFFFFFFFF),
        screenBorderColor = Color(0xFF111827),
        screenTextColor = Color(0xFF111827),
        screenExpressionColor = Color(0xFF6B7280),
        screenPreviewColor = Color(0xFF2563EB),
        cursorColor = Color(0xFF111827),
        displayFont = DisplayFontType.MONOSPACE,
        hasScanlines = false,
        numberButtonBg = Color(0xFFFFFFFF),
        numberButtonText = Color(0xFF111827),
        numberButtonBorder = Color(0xFF111827),
        operatorButtonBg = Color(0xFFFF6B8B),
        operatorButtonText = Color(0xFF111827),
        operatorButtonBorder = Color(0xFF111827),
        functionButtonBg = Color(0xFF4D96FF),
        functionButtonText = Color(0xFFFFFFFF),
        functionButtonBorder = Color(0xFF111827),
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFFFFD93D), Color(0xFFFFD93D))
        ),
        equalsButtonText = Color(0xFF111827),
        equalsButtonBorder = Color(0xFF111827),
        accentColor = Color(0xFFFFD93D),
        secondaryAccent = Color(0xFFFF6B8B),
        glowColor = Color.Transparent,
        shapeType = ButtonShapeType.BRUTALIST_RECT,
        cornerRadiusDp = 6.dp,
        borderWidthDp = 2.5.dp,
        hasShadow = false,
        isBrutalistShadow = true,
        brutalistShadowColor = Color(0xFF111827),
        pressAnimation = PressAnimationType.BRUTAL_OFFSET,
        statusBarDarkIcons = true
    )

    val CrtTerminal = ThemePalette(
        id = ThemeId.CRT_TERMINAL,
        name = "Pip-Boy CRT",
        subtitle = "Vintage phosphor green terminal with scanlines",
        category = "Retro",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF020C05), Color(0xFF05170B), Color(0xFF020C05))
        ),
        backgroundColor = Color(0xFF020C05),
        surfaceColor = Color(0xFF071F0F),
        cardBackground = Color(0xFF092914),
        screenBackground = Color(0xFF031407),
        screenBorderColor = Color(0xFF22C55E),
        screenTextColor = Color(0xFF4ADE80),
        screenExpressionColor = Color(0xFF166534),
        screenPreviewColor = Color(0xFF86EFAC),
        cursorColor = Color(0xFF22C55E),
        displayFont = DisplayFontType.DIGITAL_LCD,
        hasScanlines = true,
        numberButtonBg = Color(0xFF06230E),
        numberButtonText = Color(0xFF4ADE80),
        numberButtonBorder = Color(0x5522C55E),
        operatorButtonBg = Color(0xFF0A3315),
        operatorButtonText = Color(0xFF86EFAC),
        operatorButtonBorder = Color(0x8822C55E),
        functionButtonBg = Color(0xFF072710),
        functionButtonText = Color(0xFFBBF7D0),
        functionButtonBorder = Color(0x6622C55E),
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFF22C55E), Color(0xFF15803D))
        ),
        equalsButtonText = Color(0xFF020C05),
        accentColor = Color(0xFF22C55E),
        secondaryAccent = Color(0xFF4ADE80),
        glowColor = Color(0x5522C55E),
        shapeType = ButtonShapeType.ROUNDED_SQUARE,
        cornerRadiusDp = 8.dp,
        borderWidthDp = 1.2.dp,
        hasShadow = true,
        shadowElevationDp = 3.dp,
        pressAnimation = PressAnimationType.NEON_GLOW,
        statusBarDarkIcons = false
    )

    val MatchaZen = ThemePalette(
        id = ThemeId.MATCHA_ZEN,
        name = "Matcha & Sage",
        subtitle = "Calm organic earthy tones & soft curves",
        category = "Minimal & Aesthetic",
        isDark = false,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFFF4F7F2), Color(0xFFE8EFE5))
        ),
        backgroundColor = Color(0xFFF4F7F2),
        surfaceColor = Color(0xFFE4EDE1),
        cardBackground = Color(0xFFFFFFFF),
        screenBackground = Color(0xFFFCFDFC),
        screenBorderColor = Color(0xFFD3E0D0),
        screenTextColor = Color(0xFF2A3D27),
        screenExpressionColor = Color(0xFF7A9374),
        screenPreviewColor = Color(0xFF4E6B49),
        cursorColor = Color(0xFF52734D),
        displayFont = DisplayFontType.ROUNDED,
        hasScanlines = false,
        numberButtonBg = Color(0xFFFFFFFF),
        numberButtonText = Color(0xFF2D3E2A),
        numberButtonBorder = Color(0xFFE0EBE0),
        operatorButtonBg = Color(0xFF6B8E5F),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color.Transparent,
        functionButtonBg = Color(0xFFB8CEAF),
        functionButtonText = Color(0xFF243521),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFF4A6B3E), Color(0xFF38522E))
        ),
        equalsButtonText = Color(0xFFFFFFFF),
        accentColor = Color(0xFF6B8E5F),
        secondaryAccent = Color(0xFFB8CEAF),
        glowColor = Color(0x336B8E5F),
        shapeType = ButtonShapeType.PILL,
        cornerRadiusDp = 24.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 2.dp,
        pressAnimation = PressAnimationType.BOUNCE,
        statusBarDarkIcons = true
    )

    val SunsetGlow = ThemePalette(
        id = ThemeId.SUNSET_GLOW,
        name = "Sunset Glow",
        subtitle = "Warm twilight gradient & radiant amber",
        category = "Atmospheric",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF1E1032), Color(0xFF351540), Color(0xFF220C30))
        ),
        backgroundColor = Color(0xFF1E1032),
        surfaceColor = Color(0xFF301444),
        cardBackground = Color(0xFF421A59),
        screenBackground = Color(0xFF250F37),
        screenBorderColor = Color(0xFFFF7A59),
        screenTextColor = Color(0xFFFFD3B6),
        screenExpressionColor = Color(0xFFE29BB4),
        screenPreviewColor = Color(0xFFFF6F59),
        cursorColor = Color(0xFFFF7A59),
        displayFont = DisplayFontType.MODERN_SANS,
        hasScanlines = false,
        numberButtonBg = Color(0xFF3B1851),
        numberButtonText = Color(0xFFFFF0E6),
        numberButtonBorder = Color(0x33FF7A59),
        operatorButtonBg = Color(0xFFFF5E7E),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color.Transparent,
        functionButtonBg = Color(0xFFFF9E00),
        functionButtonText = Color(0xFF220C30),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFFFF5376), Color(0xFFFF9E00))
        ),
        equalsButtonText = Color(0xFFFFFFFF),
        accentColor = Color(0xFFFF7A59),
        secondaryAccent = Color(0xFFFF9E00),
        glowColor = Color(0x55FF5E7E),
        shapeType = ButtonShapeType.SQUIRCLE,
        cornerRadiusDp = 18.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 4.dp,
        pressAnimation = PressAnimationType.BOUNCE,
        statusBarDarkIcons = false
    )

    val OledObsidian = ThemePalette(
        id = ThemeId.OLED_OBSIDIAN,
        name = "OLED Obsidian",
        subtitle = "Pure black, titanium slate & electric blue",
        category = "Minimal & Aesthetic",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF000000), Color(0xFF040405), Color(0xFF000000))
        ),
        backgroundColor = Color(0xFF000000),
        surfaceColor = Color(0xFF0D0D0E),
        cardBackground = Color(0xFF141416),
        screenBackground = Color(0xFF080809),
        screenBorderColor = Color(0xFF27272A),
        screenTextColor = Color(0xFFFFFFFF),
        screenExpressionColor = Color(0xFF71717A),
        screenPreviewColor = Color(0xFF60A5FA),
        cursorColor = Color(0xFF3B82F6),
        displayFont = DisplayFontType.MODERN_SANS,
        hasScanlines = false,
        numberButtonBg = Color(0xFF18181B),
        numberButtonText = Color(0xFFF4F4F5),
        numberButtonBorder = Color(0xFF27272A),
        operatorButtonBg = Color(0xFF27272A),
        operatorButtonText = Color(0xFF60A5FA),
        operatorButtonBorder = Color(0x443B82F6),
        functionButtonBg = Color(0xFF27272A),
        functionButtonText = Color(0xFFA1A1AA),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFF2563EB), Color(0xFF1D4ED8))
        ),
        equalsButtonText = Color(0xFFFFFFFF),
        accentColor = Color(0xFF3B82F6),
        secondaryAccent = Color(0xFF60A5FA),
        glowColor = Color(0x333B82F6),
        shapeType = ButtonShapeType.CIRCLE,
        cornerRadiusDp = 28.dp,
        borderWidthDp = 1.dp,
        hasShadow = false,
        shadowElevationDp = 0.dp,
        pressAnimation = PressAnimationType.DEEP_SINK,
        statusBarDarkIcons = false
    )

    val PastelBubblegum = ThemePalette(
        id = ThemeId.PASTEL_BUBBLEGUM,
        name = "Bubblegum Pop",
        subtitle = "Playful marshmallow pinks & lavender pastels",
        category = "Playful",
        isDark = false,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFFFFF0F5), Color(0xFFFCE7F3), Color(0xFFF5E8FF))
        ),
        backgroundColor = Color(0xFFFFF0F5),
        surfaceColor = Color(0xFFFCE7F3),
        cardBackground = Color(0xFFFFFFFF),
        screenBackground = Color(0xFFFFFFFF),
        screenBorderColor = Color(0xFFF9A8D4),
        screenTextColor = Color(0xFF831843),
        screenExpressionColor = Color(0xFFBE185D),
        screenPreviewColor = Color(0xFF9333EA),
        cursorColor = Color(0xFFEC4899),
        displayFont = DisplayFontType.ROUNDED,
        hasScanlines = false,
        numberButtonBg = Color(0xFFFFFFFF),
        numberButtonText = Color(0xFF701A75),
        numberButtonBorder = Color(0xFFFBCFE8),
        operatorButtonBg = Color(0xFFF472B6),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color.Transparent,
        functionButtonBg = Color(0xFFC084FC),
        functionButtonText = Color(0xFFFFFFFF),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFFFB7185), Color(0xFFF43F5E))
        ),
        equalsButtonText = Color(0xFFFFFFFF),
        accentColor = Color(0xFFEC4899),
        secondaryAccent = Color(0xFFA855F7),
        glowColor = Color(0x33EC4899),
        shapeType = ButtonShapeType.SQUIRCLE,
        cornerRadiusDp = 20.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 3.dp,
        pressAnimation = PressAnimationType.BOUNCE,
        statusBarDarkIcons = true
    )

    val MonochromeLuxury = ThemePalette(
        id = ThemeId.MONOCHROME_LUXURY,
        name = "Monochrome Gold",
        subtitle = "Swiss minimalist matte charcoal & brushed gold",
        category = "Luxury & Clean",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF121316), Color(0xFF181A20), Color(0xFF101114))
        ),
        backgroundColor = Color(0xFF121316),
        surfaceColor = Color(0xFF1B1D24),
        cardBackground = Color(0xFF22242D),
        screenBackground = Color(0xFF16171D),
        screenBorderColor = Color(0xFFCA8A04),
        screenTextColor = Color(0xFFF8FAFC),
        screenExpressionColor = Color(0xFF94A3B8),
        screenPreviewColor = Color(0xFFEAB308),
        cursorColor = Color(0xFFEAB308),
        displayFont = DisplayFontType.MODERN_SANS,
        hasScanlines = false,
        numberButtonBg = Color(0xFF23252E),
        numberButtonText = Color(0xFFF1F5F9),
        numberButtonBorder = Color(0xFF333742),
        operatorButtonBg = Color(0xFF2C2F3B),
        operatorButtonText = Color(0xFFFACC15),
        operatorButtonBorder = Color(0x66CA8A04),
        functionButtonBg = Color(0xFF2A2D37),
        functionButtonText = Color(0xFFCBD5E1),
        functionButtonBorder = Color(0xFF3B404E),
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFFEAB308), Color(0xFFCA8A04))
        ),
        equalsButtonText = Color(0xFF111827),
        accentColor = Color(0xFFEAB308),
        secondaryAccent = Color(0xFFCA8A04),
        glowColor = Color(0x33EAB308),
        shapeType = ButtonShapeType.ROUNDED_SQUARE,
        cornerRadiusDp = 14.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 2.dp,
        pressAnimation = PressAnimationType.DEEP_SINK,
        statusBarDarkIcons = false
    )

    val NordicIce = ThemePalette(
        id = ThemeId.NORDIC_ICE,
        name = "Nordic Glacier",
        subtitle = "Deep arctic navy & glowing glacial cyan",
        category = "Atmospheric",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF0A192F), Color(0xFF0F2B48), Color(0xFF081426))
        ),
        backgroundColor = Color(0xFF0A192F),
        surfaceColor = Color(0xFF133658),
        cardBackground = Color(0xFF1B4975),
        screenBackground = Color(0xFF0D223C),
        screenBorderColor = Color(0xFF38BDF8),
        screenTextColor = Color(0xFFE0F2FE),
        screenExpressionColor = Color(0xFF7DD3FC),
        screenPreviewColor = Color(0xFF00E5FF),
        cursorColor = Color(0xFF38BDF8),
        displayFont = DisplayFontType.MODERN_SANS,
        hasScanlines = false,
        numberButtonBg = Color(0xFF16375B),
        numberButtonText = Color(0xFFF0F9FF),
        numberButtonBorder = Color(0x4438BDF8),
        operatorButtonBg = Color(0xFF0284C7),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color(0x6638BDF8),
        functionButtonBg = Color(0xFF0C4A6E),
        functionButtonText = Color(0xFF7DD3FC),
        functionButtonBorder = Color(0x4438BDF8),
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFF38BDF8), Color(0xFF0284C7))
        ),
        equalsButtonText = Color(0xFF081426),
        accentColor = Color(0xFF38BDF8),
        secondaryAccent = Color(0xFF0284C7),
        glowColor = Color(0x5538BDF8),
        shapeType = ButtonShapeType.SQUIRCLE,
        cornerRadiusDp = 16.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 3.dp,
        pressAnimation = PressAnimationType.BOUNCE,
        statusBarDarkIcons = false
    )

    val GameBoy8Bit = ThemePalette(
        id = ThemeId.GAMEBOY_8BIT,
        name = "Game Boy 1989",
        subtitle = "Iconic olive-green dot matrix handheld",
        category = "Retro",
        isDark = false,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFFD6D6C2), Color(0xFFC7C7B0), Color(0xFFB8B8A0))
        ),
        backgroundColor = Color(0xFFD6D6C2),
        surfaceColor = Color(0xFFC4C4AB),
        cardBackground = Color(0xFFE4E4D3),
        screenBackground = Color(0xFF8BAC0F),
        screenBorderColor = Color(0xFF306230),
        screenTextColor = Color(0xFF0F380F),
        screenExpressionColor = Color(0xFF306230),
        screenPreviewColor = Color(0xFF0F380F),
        cursorColor = Color(0xFF0F380F),
        displayFont = DisplayFontType.DIGITAL_LCD,
        hasScanlines = true,
        numberButtonBg = Color(0xFF8B004F),
        numberButtonText = Color(0xFFFFFFFF),
        numberButtonBorder = Color(0xFF5A0033),
        operatorButtonBg = Color(0xFF3A3A3A),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color(0xFF1E1E1E),
        functionButtonBg = Color(0xFF7B7B7B),
        functionButtonText = Color(0xFFFFFFFF),
        functionButtonBorder = Color(0xFF505050),
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFF9E0159), Color(0xFF6F003E))
        ),
        equalsButtonText = Color(0xFFFFFFFF),
        accentColor = Color(0xFF8B004F),
        secondaryAccent = Color(0xFF306230),
        glowColor = Color.Transparent,
        shapeType = ButtonShapeType.CIRCLE,
        cornerRadiusDp = 26.dp,
        borderWidthDp = 1.5.dp,
        hasShadow = true,
        shadowElevationDp = 3.dp,
        pressAnimation = PressAnimationType.BOUNCE,
        statusBarDarkIcons = true
    )

    val SolarizedDark = ThemePalette(
        id = ThemeId.SOLARIZED_DARK,
        name = "Solarized Dark",
        subtitle = "Ethan Schoonover's developer color harmony",
        category = "Modern Art",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF002B36), Color(0xFF073642), Color(0xFF00212B))
        ),
        backgroundColor = Color(0xFF002B36),
        surfaceColor = Color(0xFF073642),
        cardBackground = Color(0xFF0A4452),
        screenBackground = Color(0xFF001F27),
        screenBorderColor = Color(0xFF2AA198),
        screenTextColor = Color(0xFF93A1A1),
        screenExpressionColor = Color(0xFF586E75),
        screenPreviewColor = Color(0xFFB58900),
        cursorColor = Color(0xFF268BD2),
        displayFont = DisplayFontType.MONOSPACE,
        hasScanlines = false,
        numberButtonBg = Color(0xFF073642),
        numberButtonText = Color(0xFFEEE8D5),
        numberButtonBorder = Color(0xFF586E75),
        operatorButtonBg = Color(0xFFCB4B16),
        operatorButtonText = Color(0xFFFDF6E3),
        operatorButtonBorder = Color.Transparent,
        functionButtonBg = Color(0xFF268BD2),
        functionButtonText = Color(0xFFFDF6E3),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFF2AA198), Color(0xFF859900))
        ),
        equalsButtonText = Color(0xFF002B36),
        accentColor = Color(0xFF2AA198),
        secondaryAccent = Color(0xFFB58900),
        glowColor = Color(0x332AA198),
        shapeType = ButtonShapeType.ROUNDED_SQUARE,
        cornerRadiusDp = 12.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 2.dp,
        pressAnimation = PressAnimationType.DEEP_SINK,
        statusBarDarkIcons = false
    )

    val SakuraBloom = ThemePalette(
        id = ThemeId.SAKURA_BLOOM,
        name = "Sakura Blossom",
        subtitle = "Spring Tokyo cherry blossom & matcha mist",
        category = "Playful",
        isDark = false,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFFFFF7F9), Color(0xFFFDE8EE), Color(0xFFFCE1E8))
        ),
        backgroundColor = Color(0xFFFFF7F9),
        surfaceColor = Color(0xFFFCE1E8),
        cardBackground = Color(0xFFFFFFFF),
        screenBackground = Color(0xFFFFFFFF),
        screenBorderColor = Color(0xFFF4A6BE),
        screenTextColor = Color(0xFF5C2338),
        screenExpressionColor = Color(0xFF9E4B69),
        screenPreviewColor = Color(0xFFD9487D),
        cursorColor = Color(0xFFE85D88),
        displayFont = DisplayFontType.ROUNDED,
        hasScanlines = false,
        numberButtonBg = Color(0xFFFFFFFF),
        numberButtonText = Color(0xFF5C2338),
        numberButtonBorder = Color(0xFFFCD3E1),
        operatorButtonBg = Color(0xFFE85D88),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color.Transparent,
        functionButtonBg = Color(0xFF82B386),
        functionButtonText = Color(0xFFFFFFFF),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFFFF7597), Color(0xFFF43F5E))
        ),
        equalsButtonText = Color(0xFFFFFFFF),
        accentColor = Color(0xFFE85D88),
        secondaryAccent = Color(0xFF82B386),
        glowColor = Color(0x44E85D88),
        shapeType = ButtonShapeType.PILL,
        cornerRadiusDp = 24.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 3.dp,
        pressAnimation = PressAnimationType.BOUNCE,
        statusBarDarkIcons = true
    )

    val MatrixHacker = ThemePalette(
        id = ThemeId.MATRIX_HACKER,
        name = "Matrix Rain",
        subtitle = "Falling phosphor glyphs & encrypted black",
        category = "Futuristic",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF000000), Color(0xFF030D04), Color(0xFF000501))
        ),
        backgroundColor = Color(0xFF000000),
        surfaceColor = Color(0xFF061408),
        cardBackground = Color(0xFF0B210F),
        screenBackground = Color(0xFF000A02),
        screenBorderColor = Color(0xFF00FF41),
        screenTextColor = Color(0xFF00FF41),
        screenExpressionColor = Color(0xFF008F11),
        screenPreviewColor = Color(0xFF66FF88),
        cursorColor = Color(0xFF00FF41),
        displayFont = DisplayFontType.MONOSPACE,
        hasScanlines = true,
        numberButtonBg = Color(0xFF041808),
        numberButtonText = Color(0xFF00FF41),
        numberButtonBorder = Color(0x6600FF41),
        operatorButtonBg = Color(0xFF062A0E),
        operatorButtonText = Color(0xFF88FFA3),
        operatorButtonBorder = Color(0xAA00FF41),
        functionButtonBg = Color(0xFF031607),
        functionButtonText = Color(0xFF00DD36),
        functionButtonBorder = Color(0x4400FF41),
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFF00FF41), Color(0xFF008F11))
        ),
        equalsButtonText = Color(0xFF000000),
        accentColor = Color(0xFF00FF41),
        secondaryAccent = Color(0xFF66FF88),
        glowColor = Color(0x7700FF41),
        shapeType = ButtonShapeType.ROUNDED_SQUARE,
        cornerRadiusDp = 6.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 4.dp,
        pressAnimation = PressAnimationType.NEON_GLOW,
        statusBarDarkIcons = false
    )

    val AmethystRoyal = ThemePalette(
        id = ThemeId.AMETHYST_ROYAL,
        name = "Royal Amethyst",
        subtitle = "Imperial velvet violet & shimmering lilac",
        category = "Luxury & Clean",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF140826), Color(0xFF220C42), Color(0xFF110620))
        ),
        backgroundColor = Color(0xFF140826),
        surfaceColor = Color(0xFF240E47),
        cardBackground = Color(0xFF331363),
        screenBackground = Color(0xFF1A0A33),
        screenBorderColor = Color(0xFFA855F7),
        screenTextColor = Color(0xFFF3E8FF),
        screenExpressionColor = Color(0xFFC084FC),
        screenPreviewColor = Color(0xFFE9D5FF),
        cursorColor = Color(0xFFA855F7),
        displayFont = DisplayFontType.MODERN_SANS,
        hasScanlines = false,
        numberButtonBg = Color(0xFF2C1054),
        numberButtonText = Color(0xFFFAF5FF),
        numberButtonBorder = Color(0x33A855F7),
        operatorButtonBg = Color(0xFF9333EA),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color.Transparent,
        functionButtonBg = Color(0xFF7E22CE),
        functionButtonText = Color(0xFFE9D5FF),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFFA855F7), Color(0xFFD946EF))
        ),
        equalsButtonText = Color(0xFFFFFFFF),
        accentColor = Color(0xFFA855F7),
        secondaryAccent = Color(0xFFE879F9),
        glowColor = Color(0x55A855F7),
        shapeType = ButtonShapeType.SQUIRCLE,
        cornerRadiusDp = 16.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 3.dp,
        pressAnimation = PressAnimationType.BOUNCE,
        statusBarDarkIcons = false
    )

    val MacClassic1984 = ThemePalette(
        id = ThemeId.MAC_CLASSIC_1984,
        name = "Macintosh 1984",
        subtitle = "Classic desktop GUI monochrome nostalgia",
        category = "Retro",
        isDark = false,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFFEDEDED), Color(0xFFDCDCDC))
        ),
        backgroundColor = Color(0xFFEDEDED),
        surfaceColor = Color(0xFFD0D0D0),
        cardBackground = Color(0xFFFFFFFF),
        screenBackground = Color(0xFFFFFFFF),
        screenBorderColor = Color(0xFF000000),
        screenTextColor = Color(0xFF000000),
        screenExpressionColor = Color(0xFF555555),
        screenPreviewColor = Color(0xFF222222),
        cursorColor = Color(0xFF000000),
        displayFont = DisplayFontType.MONOSPACE,
        hasScanlines = false,
        numberButtonBg = Color(0xFFFFFFFF),
        numberButtonText = Color(0xFF000000),
        numberButtonBorder = Color(0xFF000000),
        operatorButtonBg = Color(0xFFEEEEEE),
        operatorButtonText = Color(0xFF000000),
        operatorButtonBorder = Color(0xFF000000),
        functionButtonBg = Color(0xFFE0E0E0),
        functionButtonText = Color(0xFF000000),
        functionButtonBorder = Color(0xFF000000),
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFF000000), Color(0xFF000000))
        ),
        equalsButtonText = Color(0xFFFFFFFF),
        equalsButtonBorder = Color(0xFF000000),
        accentColor = Color(0xFF000000),
        secondaryAccent = Color(0xFF555555),
        glowColor = Color.Transparent,
        shapeType = ButtonShapeType.ROUNDED_SQUARE,
        cornerRadiusDp = 5.dp,
        borderWidthDp = 1.5.dp,
        hasShadow = false,
        isBrutalistShadow = true,
        brutalistShadowColor = Color(0xFF000000),
        pressAnimation = PressAnimationType.BRUTAL_OFFSET,
        statusBarDarkIcons = true
    )

    val Vaporwave95 = ThemePalette(
        id = ThemeId.VAPORWAVE_95,
        name = "Vaporwave 95",
        subtitle = "Windows 95 teal, aesthetic pink & purple sunset",
        category = "Modern Art",
        isDark = false,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF008080), Color(0xFF005050))
        ),
        backgroundColor = Color(0xFF008080),
        surfaceColor = Color(0xFF006666),
        cardBackground = Color(0xFFC0C0C0),
        screenBackground = Color(0xFFC0C0C0),
        screenBorderColor = Color(0xFFFFFFFF),
        screenTextColor = Color(0xFF000080),
        screenExpressionColor = Color(0xFF800080),
        screenPreviewColor = Color(0xFFFF0080),
        cursorColor = Color(0xFF000080),
        displayFont = DisplayFontType.MONOSPACE,
        hasScanlines = false,
        numberButtonBg = Color(0xFFDFDFDF),
        numberButtonText = Color(0xFF000000),
        numberButtonBorder = Color(0xFFFFFFFF),
        operatorButtonBg = Color(0xFFFF69B4),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color(0xFFFFB6C1),
        functionButtonBg = Color(0xFF9370DB),
        functionButtonText = Color(0xFFFFFFFF),
        functionButtonBorder = Color(0xFFBA55D3),
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFFFF1493), Color(0xFF00FFFF))
        ),
        equalsButtonText = Color(0xFFFFFFFF),
        accentColor = Color(0xFFFF69B4),
        secondaryAccent = Color(0xFF00FFFF),
        glowColor = Color(0x66FF69B4),
        shapeType = ButtonShapeType.ROUNDED_SQUARE,
        cornerRadiusDp = 4.dp,
        borderWidthDp = 2.dp,
        hasShadow = true,
        shadowElevationDp = 3.dp,
        pressAnimation = PressAnimationType.BOUNCE,
        statusBarDarkIcons = false
    )

    val EspressoRoast = ThemePalette(
        id = ThemeId.ESPRESSO_ROAST,
        name = "Espresso Roast",
        subtitle = "Warm roasted hazelnut, coffee cream & dark cacao",
        category = "Atmospheric",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF1E140F), Color(0xFF2C1E17), Color(0xFF19100C))
        ),
        backgroundColor = Color(0xFF1E140F),
        surfaceColor = Color(0xFF2D1F17),
        cardBackground = Color(0xFF3B2A20),
        screenBackground = Color(0xFF241812),
        screenBorderColor = Color(0xFFD4A373),
        screenTextColor = Color(0xFFFAEDCD),
        screenExpressionColor = Color(0xFFCCD5AE),
        screenPreviewColor = Color(0xFFE9EDC9),
        cursorColor = Color(0xFFD4A373),
        displayFont = DisplayFontType.ROUNDED,
        hasScanlines = false,
        numberButtonBg = Color(0xFF38271E),
        numberButtonText = Color(0xFFFEFAE0),
        numberButtonBorder = Color(0x33D4A373),
        operatorButtonBg = Color(0xFFB07D62),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color.Transparent,
        functionButtonBg = Color(0xFF895737),
        functionButtonText = Color(0xFFFEFAE0),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFFD4A373), Color(0xFFA67C52))
        ),
        equalsButtonText = Color(0xFF1E140F),
        accentColor = Color(0xFFD4A373),
        secondaryAccent = Color(0xFFB07D62),
        glowColor = Color(0x33D4A373),
        shapeType = ButtonShapeType.SQUIRCLE,
        cornerRadiusDp = 16.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 2.dp,
        pressAnimation = PressAnimationType.BOUNCE,
        statusBarDarkIcons = false
    )

    val LavaMagma = ThemePalette(
        id = ThemeId.LAVA_MAGMA,
        name = "Lava Magma",
        subtitle = "Volcanic obsidian & molten fiery amber",
        category = "Futuristic",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF120908), Color(0xFF1C0F0A), Color(0xFF0D0606))
        ),
        backgroundColor = Color(0xFF120908),
        surfaceColor = Color(0xFF1F110B),
        cardBackground = Color(0xFF2C1811),
        screenBackground = Color(0xFF160B08),
        screenBorderColor = Color(0xFFFF5500),
        screenTextColor = Color(0xFFFF9E00),
        screenExpressionColor = Color(0xFFFF6B35),
        screenPreviewColor = Color(0xFFFFD60A),
        cursorColor = Color(0xFFFF5500),
        displayFont = DisplayFontType.MONOSPACE,
        hasScanlines = false,
        numberButtonBg = Color(0xFF24130D),
        numberButtonText = Color(0xFFFFEBD0),
        numberButtonBorder = Color(0x44FF5500),
        operatorButtonBg = Color(0xFF9E1F00),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color.Transparent,
        functionButtonBg = Color(0xFF4A1A0C),
        functionButtonText = Color(0xFFFF9E00),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFFFF3D00), Color(0xFFFF9100))
        ),
        equalsButtonText = Color(0xFFFFFFFF),
        accentColor = Color(0xFFFF5500),
        secondaryAccent = Color(0xFFFF9E00),
        glowColor = Color(0x66FF5500),
        shapeType = ButtonShapeType.SQUIRCLE,
        cornerRadiusDp = 14.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 4.dp,
        pressAnimation = PressAnimationType.NEON_GLOW,
        statusBarDarkIcons = false
    )

    val CosmicAurora = ThemePalette(
        id = ThemeId.COSMIC_AURORA,
        name = "Cosmic Aurora",
        subtitle = "Deep space indigo & polar borealis glow",
        category = "Atmospheric",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF07091A), Color(0xFF0B112C), Color(0xFF050614))
        ),
        backgroundColor = Color(0xFF07091A),
        surfaceColor = Color(0xFF0E1638),
        cardBackground = Color(0xFF14204D),
        screenBackground = Color(0xFF080C22),
        screenBorderColor = Color(0xFF00F5D4),
        screenTextColor = Color(0xFF00F5D4),
        screenExpressionColor = Color(0xFF9D4EDD),
        screenPreviewColor = Color(0xFFE0AAFF),
        cursorColor = Color(0xFF00F5D4),
        displayFont = DisplayFontType.MODERN_SANS,
        hasScanlines = false,
        numberButtonBg = Color(0xFF10163A),
        numberButtonText = Color(0xFFE0AAFF),
        numberButtonBorder = Color(0x3300F5D4),
        operatorButtonBg = Color(0xFF5A189A),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color.Transparent,
        functionButtonBg = Color(0xFF0F3846),
        functionButtonText = Color(0xFF00F5D4),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFF00F5D4), Color(0xFF7B2CBF))
        ),
        equalsButtonText = Color(0xFF07091A),
        accentColor = Color(0xFF00F5D4),
        secondaryAccent = Color(0xFFE0AAFF),
        glowColor = Color(0x6600F5D4),
        shapeType = ButtonShapeType.PILL,
        cornerRadiusDp = 20.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 3.dp,
        pressAnimation = PressAnimationType.BOUNCE,
        statusBarDarkIcons = false
    )

    val MidnightTokyo = ThemePalette(
        id = ThemeId.MIDNIGHT_TOKYO,
        name = "Midnight Tokyo",
        subtitle = "Shinjuku neon nightlife & electric ultraviolet",
        category = "Modern Art",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF0A0612), Color(0xFF140C24), Color(0xFF08040F))
        ),
        backgroundColor = Color(0xFF0A0612),
        surfaceColor = Color(0xFF180F2E),
        cardBackground = Color(0xFF241642),
        screenBackground = Color(0xFF11091F),
        screenBorderColor = Color(0xFFF72585),
        screenTextColor = Color(0xFF4CC9F0),
        screenExpressionColor = Color(0xFFB5179E),
        screenPreviewColor = Color(0xFF7209B7),
        cursorColor = Color(0xFFF72585),
        displayFont = DisplayFontType.MONOSPACE,
        hasScanlines = false,
        numberButtonBg = Color(0xFF1A1030),
        numberButtonText = Color(0xFFF0F3F8),
        numberButtonBorder = Color(0x33F72585),
        operatorButtonBg = Color(0xFF7209B7),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color.Transparent,
        functionButtonBg = Color(0xFF3A0CA3),
        functionButtonText = Color(0xFF4CC9F0),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFFF72585), Color(0xFF4CC9F0))
        ),
        equalsButtonText = Color(0xFFFFFFFF),
        accentColor = Color(0xFFF72585),
        secondaryAccent = Color(0xFF4CC9F0),
        glowColor = Color(0x66F72585),
        shapeType = ButtonShapeType.ROUNDED_SQUARE,
        cornerRadiusDp = 14.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 4.dp,
        pressAnimation = PressAnimationType.BOUNCE,
        statusBarDarkIcons = false
    )

    val EmeraldForest = ThemePalette(
        id = ThemeId.EMERALD_FOREST,
        name = "Emerald Forest",
        subtitle = "Deep botanical velvet moss & golden accents",
        category = "Luxury & Clean",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF06140D), Color(0xFF0A2216), Color(0xFF05100B))
        ),
        backgroundColor = Color(0xFF06140D),
        surfaceColor = Color(0xFF0D2B1C),
        cardBackground = Color(0xFF133B27),
        screenBackground = Color(0xFF081B12),
        screenBorderColor = Color(0xFF2EC4B6),
        screenTextColor = Color(0xFFCBF3F0),
        screenExpressionColor = Color(0xFF52B788),
        screenPreviewColor = Color(0xFFE7C6FF),
        cursorColor = Color(0xFF2EC4B6),
        displayFont = DisplayFontType.ROUNDED,
        hasScanlines = false,
        numberButtonBg = Color(0xFF0F2D1E),
        numberButtonText = Color(0xFFE9F5ED),
        numberButtonBorder = Color(0x3352B788),
        operatorButtonBg = Color(0xFF2D6A4F),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color.Transparent,
        functionButtonBg = Color(0xFF1B4332),
        functionButtonText = Color(0xFF74C69D),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFF2EC4B6), Color(0xFF52B788))
        ),
        equalsButtonText = Color(0xFF06140D),
        accentColor = Color(0xFF2EC4B6),
        secondaryAccent = Color(0xFF74C69D),
        glowColor = Color(0x442EC4B6),
        shapeType = ButtonShapeType.SQUIRCLE,
        cornerRadiusDp = 16.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 3.dp,
        pressAnimation = PressAnimationType.DEEP_SINK,
        statusBarDarkIcons = false
    )

    val SteampunkBrass = ThemePalette(
        id = ThemeId.STEAMPUNK_BRASS,
        name = "Steampunk Brass",
        subtitle = "Victorian gears, aged copper & parchment",
        category = "Retro",
        isDark = true,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFF1B130E), Color(0xFF281D15), Color(0xFF140E0A))
        ),
        backgroundColor = Color(0xFF1B130E),
        surfaceColor = Color(0xFF2A1E16),
        cardBackground = Color(0xFF38291F),
        screenBackground = Color(0xFF2B2017),
        screenBorderColor = Color(0xFFC68B59),
        screenTextColor = Color(0xFFE8C39E),
        screenExpressionColor = Color(0xFFB07D62),
        screenPreviewColor = Color(0xFFF3E9D2),
        cursorColor = Color(0xFFC68B59),
        displayFont = DisplayFontType.DIGITAL_LCD,
        hasScanlines = false,
        numberButtonBg = Color(0xFF36271D),
        numberButtonText = Color(0xFFF5EBE0),
        numberButtonBorder = Color(0x44C68B59),
        operatorButtonBg = Color(0xFF8C5336),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color.Transparent,
        functionButtonBg = Color(0xFF5C3D2E),
        functionButtonText = Color(0xFFE8C39E),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFFC68B59), Color(0xFF8C5336))
        ),
        equalsButtonText = Color(0xFFFFFFFF),
        accentColor = Color(0xFFC68B59),
        secondaryAccent = Color(0xFFE8C39E),
        glowColor = Color(0x44C68B59),
        shapeType = ButtonShapeType.ROUNDED_SQUARE,
        cornerRadiusDp = 12.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 3.dp,
        pressAnimation = PressAnimationType.DEEP_SINK,
        statusBarDarkIcons = false
    )

    val CottonCandy = ThemePalette(
        id = ThemeId.COTTON_CANDY,
        name = "Cotton Candy",
        subtitle = "Pastel sky blue, fluffy peach & lavender dream",
        category = "Playful",
        isDark = false,
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(Color(0xFFF3F8FF), Color(0xFFFDF2F8), Color(0xFFEFF6FF))
        ),
        backgroundColor = Color(0xFFF3F8FF),
        surfaceColor = Color(0xFFFFFFFF),
        cardBackground = Color(0xFFF8FAFC),
        screenBackground = Color(0xFFFFFFFF),
        screenBorderColor = Color(0xFFF472B6),
        screenTextColor = Color(0xFF3B82F6),
        screenExpressionColor = Color(0xFFEC4899),
        screenPreviewColor = Color(0xFF8B5CF6),
        cursorColor = Color(0xFFF472B6),
        displayFont = DisplayFontType.ROUNDED,
        hasScanlines = false,
        numberButtonBg = Color(0xFFFFFFFF),
        numberButtonText = Color(0xFF1E293B),
        numberButtonBorder = Color(0x33F472B6),
        operatorButtonBg = Color(0xFFEC4899),
        operatorButtonText = Color(0xFFFFFFFF),
        operatorButtonBorder = Color.Transparent,
        functionButtonBg = Color(0xFFE0E7FF),
        functionButtonText = Color(0xFF4F46E5),
        functionButtonBorder = Color.Transparent,
        equalsButtonBrush = Brush.linearGradient(
            colors = listOf(Color(0xFF38BDF8), Color(0xFFF472B6))
        ),
        equalsButtonText = Color(0xFFFFFFFF),
        accentColor = Color(0xFFF472B6),
        secondaryAccent = Color(0xFF38BDF8),
        glowColor = Color(0x33F472B6),
        shapeType = ButtonShapeType.PILL,
        cornerRadiusDp = 20.dp,
        borderWidthDp = 1.dp,
        hasShadow = true,
        shadowElevationDp = 2.dp,
        pressAnimation = PressAnimationType.BOUNCE,
        statusBarDarkIcons = true
    )

    val allThemes: List<ThemePalette> = listOf(
        Cyberpunk,
        Synthwave,
        NeoBrutalism,
        CrtTerminal,
        MatchaZen,
        SunsetGlow,
        OledObsidian,
        PastelBubblegum,
        MonochromeLuxury,
        NordicIce,
        GameBoy8Bit,
        SolarizedDark,
        SakuraBloom,
        MatrixHacker,
        AmethystRoyal,
        MacClassic1984,
        Vaporwave95,
        EspressoRoast,
        LavaMagma,
        CosmicAurora,
        MidnightTokyo,
        EmeraldForest,
        SteampunkBrass,
        CottonCandy
    )

    fun getThemeById(id: ThemeId): ThemePalette {
        return allThemes.find { it.id == id } ?: Cyberpunk
    }
}
